const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');
const {AiService}=require('./ai-service.cjs');const {normalizeUsage,cliUsageParser}=require('./ai-usage.cjs');const {callOpenAI}=require('./openai-provider.cjs');
test('usage keeps cached/reasoning as subsets and missing distinct from zero',()=>{assert.equal(normalizeUsage(null),null);assert.equal(normalizeUsage({input_tokens:1}),null);assert.deepEqual(normalizeUsage({input_tokens:100,output_tokens:20,input_tokens_details:{cached_tokens:80},output_tokens_details:{reasoning_tokens:5}}),{input:100,output:20,total:120,cached:80,reasoning:5});assert.equal(normalizeUsage({input_tokens:0,output_tokens:0}).total,0);});
test('CLI JSONL parser handles chunks, multiple turns, unicode and unterminated final line',()=>{const parser=cliUsageParser();const bytes=Buffer.from('not json\n'+JSON.stringify({type:'item.completed',text:'測試'})+'\n'+JSON.stringify({type:'turn.completed',usage:{input_tokens:100,cached_input_tokens:80,output_tokens:20,reasoning_output_tokens:5}})+'\n'+JSON.stringify({type:'turn.completed',usage:{input_tokens:10,cached_input_tokens:0,output_tokens:2,reasoning_output_tokens:0}}));for(let i=0;i<bytes.length;i+=7)parser.push(bytes.subarray(i,i+7));assert.deepEqual(parser.finish(),{input:110,output:22,total:132,cached:80,reasoning:5});assert.equal(cliUsageParser().finish(),null);});
const complete={status:'completed',model:'test-model',output:[{type:'reasoning',content:[]},{type:'message',content:[{type:'output_text',text:'測試回覆'}]}],usage:{input_tokens:17,output_tokens:9,total_tokens:26,input_tokens_details:{cached_tokens:0},output_tokens_details:{reasoning_tokens:2}}};
test('Responses request uses fixed origin, no storage/tools and handles reported usage',async()=>{let body;const result=await callOpenAI({key:'unit-test-key',model:'test-model',text:'untrusted',instructions:'translate',fetchImpl:async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(options.redirect,'error');assert.equal(options.headers.Authorization,'Bearer unit-test-key');body=JSON.parse(options.body);return new Response(JSON.stringify(complete));}});assert.equal(body.store,false);assert.equal(body.tools,undefined);assert.equal(JSON.parse(body.input).source,'untrusted');assert.equal(result.text,'測試回覆');assert.equal(result.usage.total,26);});
test('HTTP errors never expose the raw response and incomplete output retains usage',async()=>{await assert.rejects(callOpenAI({fetchImpl:async()=>new Response('secret-key-server-echo',{status:401})}),e=>e.message.includes('401')&&!e.message.includes('secret-key'));await assert.rejects(callOpenAI({fetchImpl:async()=>new Response(JSON.stringify({...complete,status:'incomplete'}))}),e=>e.usage.total===26&&e.message.includes('未完成'));});
function vault(){const key=crypto.randomBytes(32);return {isEncryptionAvailable:()=>true,encryptString:value=>{const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv);const bytes=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),bytes]);},decryptString:bytes=>{const decipher=crypto.createDecipheriv('aes-256-gcm',key,bytes.subarray(0,12));decipher.setAuthTag(bytes.subarray(12,28));return Buffer.concat([decipher.update(bytes.subarray(28)),decipher.final()]).toString('utf8');}};}
test('API provider works without CLI, protects keys, supports cancellation and key removal',async()=>{
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'cangshu-api-test-'));const key='sk-unit-test-placeholder';let waiting=false;
 try{const service=new AiService(directory,{safeStorage:vault(),fetchImpl:async(_url,options)=>{if(!waiting)return new Response(JSON.stringify(complete));return new Promise((_resolve,reject)=>options.signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError'))));}});service.executable=()=>{throw Error('CLI must not run');};
 await service.configure({provider:'openai-api',apiModel:'test-model',apiKey:key});const settings=await fs.readFile(service.settingsFile,'utf8');assert.ok(!settings.includes(key));assert.ok(!(await fs.readFile(service.keyFile)).includes(Buffer.from(key)));assert.ok(!JSON.stringify(await service.check()).includes(key));
 const result=await service.run({action:'translate',text:'sample'});assert.equal(result.provider,'openai-api');assert.equal(result.usage.total,26);
 await service.configure({apiKey:''});assert.equal(await service.apiKey(),key);
 waiting=true;const running=service.run({action:'summarize',text:'sample'});await new Promise(r=>setTimeout(r,25));service.cancel();await assert.rejects(running,/已取消/);assert.equal(service.job,null);
 await service.configure({removeKey:true});assert.equal((await service.info()).hasApiKey,false);await assert.rejects(service.run({action:'explain',text:'sample'}),/金鑰/);
 const insecure=new AiService(directory,{safeStorage:{isEncryptionAvailable:()=>false}});await assert.rejects(insecure.configure({apiKey:key}),/加密/);
 }finally{for(const f of ['ai-settings.json','openai-key.bin','openai-key.bin.tmp'])await fs.unlink(path.join(directory,f)).catch(()=>{});await fs.rmdir(directory);}
});
